server:
  port: 8005

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.106:8848
    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: SEATA_GROUP
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.106:3306/seata_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: gwang

mybatis:
  type-aliases-package: com.wanggang.alibaba.entity
  mapper-locations: classpath*:mapper/*.xml

feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info