server:
  port: 6001

spring:
  application:
    name: cloudalibaba-redis-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.104:8848  # 配置nacos服务地址
    sentinel:
      transport:
        dashboard: 192.168.0.104:8080   # 配置sentinel服务地址
        port: 8719
  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.104:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: gwang
# mycat
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.104:8066/TEST?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
#    username: mycat
#    password: gwang
  redis:
    password: gwang  # Redis服务器连接密码（默认为空）
    database: 0  # Redis数据库索引（默认为0）
    timeout: 10000  # 连接超时时间（毫秒）
# jedis 连接池
#    jedis:
#      pool:
#        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8   # 连接池中的最大空闲连接
#        min-idle: 0   # 连接池中的最小空闲连接
# lettuce 连接池（默认）
    lettuce:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 500ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 16   # 连接池中的最大空闲连接
        min-idle: 8  # 连接池中的最小空闲连接

# 单机配置
#    host: 192.168.0.104  # Redis服务器地址
#    port: 6379  # Redis服务器连接端口

# Cluster集群配置
#    cluster:
#      nodes: 192.168.0.104:6379,192.168.0.104:6380,192.168.0.104:6381,192.168.0.104:6382
#      max-redirects: 3  # 重定向的最大次数

# Sentinel集群配置
    sentinel:
      master: mymaster
      nodes: 192.168.0.104:26379,192.168.0.104:26380,192.168.0.104:26381,192.168.0.104:26382

mybatis:
  type-aliases-package: com.wanggang.alibaba.entity
  mapper-locations: classpath*:mapper/*.xml