server:
  port: 1001

spring:
  application:
    name: nacos-user-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.106:8848  # 配置nacos服务地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: gwang

mybatis:
  type-aliases-package: com.wanggang.alibaba.entity
  mapper-locations: classpath*:mapper/*.xml

management:
  endpoint:
    web:
      exposure:
        include: '*'

service-url:
  nacos-order-service: http://nacos-order-service

